# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
addons:
  apt_packages:
    - libgmp-dev
notifications:
  email: false
before_script:
  - julia -e 'Pkg.clone("git://github.com/blegat/Polyhedra.jl.git")'
# uncomment the following lines to override the default test script
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("cddlib"); Pkg.test("cddlib"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("CDD")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
